name: "docspec"
version: "0.0.1"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "Package description here."
requirements:
  - python ^3.4
  - nr.databind.core ~0.0.13
  - nr.databind.json ~0.0.9
